version: '2'
services:
    nearep-app:
        image: nearep
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://nearep-mysql:3306/nearep?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    nearep-mysql:
        extends:
            file: mysql.yml
            service: nearep-mysql
